# Generated by Django 5.1 on 2025-10-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Precio', models.IntegerField()),
                ('Cantidad', models.IntegerField()),
            ],
        ),
    ]
